// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.21.12
// source: auth.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "auth";

/** Request messages remain the same */
export interface LoginRequest {
}

export interface SignUpRequest {
}

export interface LogoutRequest {
}

export interface RefreshTokenRequest {
}

export interface ResetPasswordRequest {
}

/** Updated response messages */
export interface AuthResponse {
  success?: AuthSuccess | undefined;
  error?: ErrorResponse | undefined;
}

export interface AuthSuccess {
  accessToken: string;
  refreshToken: string;
  user: UserData | undefined;
}

export interface UserData {
  id: string;
  email: string;
  name: string;
}

export interface LogoutResponse {
  success?: LogoutSuccess | undefined;
  error?: ErrorResponse | undefined;
}

export interface LogoutSuccess {
  success: boolean;
}

export interface ResetPasswordResponse {
  success?: ResetPasswordSuccess | undefined;
  error?: ErrorResponse | undefined;
}

export interface ResetPasswordSuccess {
  success: boolean;
}

export interface ErrorResponse {
  /** gRPC status code */
  code: number;
  /** User-friendly message */
  message: string;
  /** Field-specific errors */
  errors: ErrorDetail[];
  /** ISO timestamp */
  timestamp: string;
}

export interface ErrorDetail {
  /** Which field caused error */
  field: string;
  /** Field-specific message */
  message: string;
  /** Machine-readable code */
  code: string;
}

export const AUTH_PACKAGE_NAME = "auth";

export interface AuthServiceClient {
  login(request: LoginRequest): Observable<AuthResponse>;

  signUp(request: SignUpRequest): Observable<AuthResponse>;

  logout(request: LogoutRequest): Observable<LogoutResponse>;

  refreshToken(request: RefreshTokenRequest): Observable<AuthResponse>;

  resetPassword(request: ResetPasswordRequest): Observable<ResetPasswordResponse>;
}

export interface AuthServiceController {
  login(request: LoginRequest): Promise<AuthResponse> | Observable<AuthResponse> | AuthResponse;

  signUp(request: SignUpRequest): Promise<AuthResponse> | Observable<AuthResponse> | AuthResponse;

  logout(request: LogoutRequest): Promise<LogoutResponse> | Observable<LogoutResponse> | LogoutResponse;

  refreshToken(request: RefreshTokenRequest): Promise<AuthResponse> | Observable<AuthResponse> | AuthResponse;

  resetPassword(
    request: ResetPasswordRequest,
  ): Promise<ResetPasswordResponse> | Observable<ResetPasswordResponse> | ResetPasswordResponse;
}

export function AuthServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["login", "signUp", "logout", "refreshToken", "resetPassword"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const AUTH_SERVICE_NAME = "AuthService";
